### ISSUE TITLE
[FEATURE] Multi-level expand

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-repository#26]
### Description

I would like to be able to do multi-level expand in case of `many-to-many` association.
For example, in case of user to user role association, where many users can have many roles. I would like to do two level expand to get not only role ID but also role name. As far as I can see, it's not possible to do that right now.
Also, when using `find()` and `findOne()` methods without the `builder`, it would be nice to include selected associations.

### Suggested solution

`getExpand()` could be called the following way:
```ts
const usersWithRoles = await userRepo.builder().find({email}).getExpand('roles.userRole').limit({limit: 1}).execute();
```

PS: full-blown ORM functionality, where calling associated properties of an entity retrieved with `find()` or `findOne()` would automatically load the associated entities would be really cool. Like in dotnet EntityFramework.

**Comment by dragolea** [comment]
Hi Tomas,
We are aware of the `deep expand`, but unfortunately, so far I have not been able to find a good solution to that.

Regarding your suggested solution : 

```ts
.getExpand('roles.userRole')
```
We cannot apply TS typing if we implement like above

CDS-TS-Dispatcher & CDS-TS-Repository rely on the Standard SAP CDS-Typer package and we must follow their rules, that package (CDS-Typer focuses on JS mainly and as second place on the TS), and sometimes is really hard to find a good solution.


CDS-TS-Repository is more like a Library not an ORM, similar to SPRING DATA JPA which eases the development of by offering out-of-the-box actions on the persistence level.

Let's leave this issue open for the moment as I will put some effort into finding a good solution.

Really appreciate your effort by providing us good hints,
Daniel

**Comment by hakimio** [comment]
> We cannot apply TS typing if we implement like above

Is it just an issue with typing for special column names like `roles.userRole`? If that's the case, maybe we could use [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) to find solution for this. 

Anyway, I understand that it's not a trivial request and I am looking into possible workarounds for this.
One obvious solution would be to expand the repository with custom query:
```ts
@Repository()
export class UserRepository extends BaseRepository<User> {

    constructor() {
        super(User);
    }

    getUserWithRoles(email: User['email']): Promise<User> {
        return SELECT.one
            .from(this.entity, user => {
                user('*');
                user.roles!(usersUserRole => {
                    usersUserRole.userRole!(role => {
                        role('*');
                    });
                });
            })
            .where({email});
    }

}
```

As another workaround maybe it would be possible to expand the schema definition with calculated field or some association which would allow to use `getExpand()` to get an array of associated roles directly? With my limited experience with CDS I couldn't come-up with anything like that, maybe you have some suggestions?
Here is basic definition of the schema:
```cds
entity Users : cuid, managed {
    name         : String(255);
    username     : String(255);
    roles        : Composition of many UsersUserRoles on roles.user = $self;
}

entity UsersUserRoles {
    key user: Association to Users;
    key userRole: Association to UserRoles;
}

entity UserRoles : cuid {
    name        : String(255);
    description : String(500);
    users       : Composition of many UsersUserRoles on users.userRole = $self;
}
```

**Comment by dragolea** [comment]
Having a new custom method in the Repository is totally fine when the provided ones do not satisfy your needs.
 
Using template literals is a nice TS feature but in our case, it will not look that nice, we need something like an object 
```ts
{
   parent : 'ShoppingCart', // begin of the expand, we assume that `ShoppingCart` is an association in `MyEntity`.
   children1 : 'Order', // one of the association of 'ShoppingCart' expanded
   children2 : 'Items' // one of the association of the 'Order' expanded 
} 
```
But for the moment I do not know what's the best approach.

I am not a CDS guy, I write very little CDS.

**Comment by hakimio** [comment]
Other possible ideas just for inspiration:
```js
getExpand({
    ShoppingCart: {
        Order: {
            Items: {} // "null" or anything "falsy" could work
        }
    }
})


getExpand({
    ShoppingCart: {
        Order: 'Items'
    }
})
```

Should be possible to type correctly as well.

**Comment by hakimio** [comment]
Found a nice client side odata query library written in TS: [angular-odata](https://github.com/diegomvh/angular-odata).
They have a very nice fully typed expand functionality:
```ts
    people
      .query((q) =>
        q.expand({
          Friends: {
            expand: { Friends: { select: ["AddressInfo"] } },
          },
          Trips: { select: ["Name", "Tags"] },
        })
      )
```
- you get IDE auto-completion for `expand()` parameter object keys (`expand({ Friends: {} })`) and also column names are aut-completed in `select` column array.
- Empty object can be used to select all columns of the child entity (`expand({ Friends: {} }`)

Imho, that's a very intuitive design.

**Comment by dragolea** [comment]
Thanks, I will have a look over expand.

**Comment by hakimio** [comment]
Awesome. Looking at the readme, the API looks very convenient :)
I'll test it out tomorrow and will let you know if it's working as expected.

**Comment by hakimio** [comment]
Minor readme nitpick. Comment doesn't correspond the code:
```js
     // expand 'genre', having only 'ID' and 'name'
    genre: {
      select: ['ID', 'parent'],
    },
```
I guess it should be `select: ['ID', 'name']` instead of `select: ['ID', 'parent']`.

**Comment by hakimio** [comment]
@dragolea 
The new expand functionality works great. Just a small feature request: it would be nice if in addition to `builder().find()`, we would also have `builder().findOne()` like we have `SELECT.one` from SAP.
Using `{limit: 1}` is not very convenient:
```ts
const users = await this.builder()
    .find({ email })
    .limit({ limit: 1 })
    .execute();
    
const user = users?.[0];
```
vs
```ts
const user = await this.builder()
    .findOne({ email })
    .execute();
```

**Comment by dragolea** [comment]
@hakimio You practically read my mind, I actually started to work on this new builder (findOne) :) 
Are you kind and open a new issue for that and briefly just copy the above message in a new issue.

**Comment by hakimio** [comment]
I have created a new feature request: https://github.com/dxfrontier/cds-ts-repository/issues/40
Your proposed implementation sounds great 🙂
