### ISSUE TITLE
[FEATURE] Auto expand / Auto expose associations / compositions when getExpand() is used

### ISSUE THREAD

**Issue by dragolea** [dxfrontier/cds-ts-repository#38]
### Description

Auto expand all association/compositions when `getExpand({ levels : number })` is used.

```ts
const results = await this.builder()
  .find({
    name: 'A company name',
  })
  .getExpand({ levels : 2 })
  .execute();
```

### Suggested solution

Currently, SAP offers us the `Projection` method to expand an association from an entity :

```ts
 getUserWithRoles(email: User['email']): Promise<User> {
      return SELECT.one
          .from(this.entity, user => {
              user('*');
              user.roles!(usersUserRole => {
                  usersUserRole.userRole!(role => {
                      role('*');
                  });
              });
          })
          .where({email});
  }
```

To have auto expand of all associations from the entity `without need to mention them` we need to loop over the `MyEntity.elements` where all fields can be found then check which element is an association/composition and build the logic for auto expose / auto expand of the associations.

The following should be `excluded` from expanding :  
- texts, currency, DraftAdministrativeData, SiblingEntity` associations

**Comment by hakimio** [comment]
Isn't this the same like recently closed https://github.com/dxfrontier/cds-ts-repository/issues/26?

**Comment by dragolea** [comment]
Nope, this is just a placeholder for a wish from our internal team.

**Comment by dragolea** [comment]
hi @hakimio,
Let me know what you think about the new overload for getExpand method.

[Auto expand - getExpand](https://github.com/dxfrontier/cds-ts-repository?tab=readme-ov-file#getexpand)

**Comment by hakimio** [comment]
It's a nice convenience feature but I would most likely still prefer to manually specify columns to expand for better performance.

**Comment by dragolea** [comment]
Indeed, for performance reasons is better to use the manual deep expand.
