### ISSUE TITLE
[FEATURE] `builder().findOne()` method

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-repository#40]
### Description

It would be nice if the `builder` would provide `findOne()` method.
Right now the only workaround is to use `find()` with `limit({ limit: 1 })` which is not very convenient:
```ts
const users = await this.builder()
    .find({ email })
    .limit({ limit: 1 })
    .execute();
    
const user = users?.[0];
```

### Suggested solution

`builder().findOne()` method which returns single entity instance instead of an array:
```ts
const user = await this.builder()
    .findOne({ email })
    .execute();
```

**Comment by dragolea** [comment]
Hi @hakimio 
New findOne builder released.
Have a look over readme : [findOne](https://github.com/dxfrontier/cds-ts-repository?tab=readme-ov-file#findone-1)

**Comment by hakimio** [comment]
Thanks. `findOne()` works great. 
Just in the readme you forgot to mention that `findOne()` also provides `getExpand()` method.

**Comment by dragolea** [comment]
Thanks for noticing.
I will add it.
