### ISSUE TITLE
[BUG] `Filter` does not support `is null` and `is not null` conditions

### ISSUE THREAD

**Issue by hakimio** [dxfrontier/cds-ts-repository#80]
### Current behavior

`Filter` does not support `is null` or `is not null` conditions.

### Expected behavior

`Filter` supports `is null` or `is not null` conditions.

### Steps to reproduce

Following filters all result in errors:
```ts
const filter = new Filter<Book>({  field: 'currency_code',  operator: 'IS',  value: null });
const filter2 = new Filter<Book>({  field: 'currency_code',  operator: 'IS NOT',  value: null });
const filter3 = new Filter<Book>({  field: 'currency_code',  operator: 'EQUALS',  value: null });
const filter4 = new Filter<Book>({  field: 'currency_code',  operator: 'NOT EQUAL',  value: null });
```

Also, it might make sense to allow `boolean` as `Filter` value.

### Environment

- **@dxfrontier packages**:
"@dxfrontier/cds-ts-dispatcher": "2.1.4"
"@dxfrontier/cds-ts-repository": "1.1.3"
- **node** 20.13.1
- **npm** 10.8.1

**Comment by dragolea** [comment]
This is a nice feature.
I will have a look over it, I think it make sense to have it there.

**Comment by hakimio** [comment]
@dragolea can you also add `boolean` to `FilterValue`?

**Comment by dragolea** [comment]
Ok, sure

**Comment by hakimio** [comment]
Thanks.

**Comment by hakimio** [comment]
@dragolea unfortunately `NOT EQUAL null` doesn't work with `PostgreSQL` date fields. I get `invalid input syntax for type date: "null"` error.
Can you add support for `IS NULL` and `IS NOT NULL` filters?
